name: elevateshop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.4.3
  cupertino_icons: ^1.0.2
  faker: ^2.0.0
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_cli: ^1.8.1
  google_nav_bar: ^5.0.6
  http: ^0.13.5
  image_picker: ^0.8.6+4
  path: ^1.8.1
  path_provider: ^2.0.13

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  fluttertoast: ^8.2.1
  shared_preferences: ^2.0.17

flutter:
  assets:
    - assets/
  uses-material-design: true
